#!/bin/sh
# valid-toml
# Copyright (c) 2023 Tom Marble
# See LICENSE for details.

dir=$(dirname $0)
program=$(basename $0)
build="$dir/../build"
files=$dir/$program.txt
passed="$build/${program}-passed.txt"
skipped="$dir/${program}-skipped.txt"

mkdir -p "$build"

if [ -z "$TOML_TEST" ]; then
    echo "Please export TOML_TEST=/path/to/src/github/BurntSushi/toml-test"
    exit 1
fi

if [ ! -e "$files" ]; then
    echo "cannot find files: $files"
    exit 1
fi

if [ ! -e "$skipped" ]; then
    touch "$skipped"
fi

if [ ! -e "$passed" ]; then
    touch "$passed"
fi

for file in $(cat $files); do
    if grep "$file" "$skipped" > /dev/null; then
        continue
    fi
    if grep "$file" "$passed" > /dev/null; then
        continue
    fi
    echo $file
    debug="$build/output.err"
    output="$build/output.toml"
    if ! mmp.py -v -T -r "$TOML_TEST/$file" -o "$output" > "$debug" 2>&1 ; then
        echo "FAILED"
        exit 1
    fi
    # if ! diff -u --ignore-space-change "$file" "$output" ; then
    if ! diff -u "$TOML_TEST/$file" "$output" ; then
        echo "NOT SAME"
        exit 2
    fi
    echo "$file" >> "$passed"
    rm "$output" "$debug"
done
